from django.urls import path

from api.views import (
    DownloadShoppingCartView,
    FavoriteView,
    IngredientDetailView,
    IngredientListView,
    RecipeDetailView,
    RecipeListView,
    ShoppingView,
    SubscribeView,
    SubscribtionView,
    TagDetailView,
    TagListView,
    TokenCreateView,
    TokenDestroyView,
    UserDetailView,
    UserMeView,
    UserListView,
    UserPasswordView,
)

app_name = 'api'

urlpatterns = [
    path(
        route='auth/token/login/',
        view=TokenCreateView.as_view(),
        name='auth-signin'
    ),
    path(
        route='auth/token/logout/',
        view=TokenDestroyView.as_view(),
        name='auth-signout'
    ),
    path(
        route='users/',
        view=UserListView.as_view(),
        name='user-list'
    ),
    path(
        route='users/me/',
        view=UserMeView.as_view(),
        name='user-me'
    ),
    path(
        route='users/set_password/',
        view=UserPasswordView.as_view(),
        name='user-password'
    ),
    path(
        route='users/subscriptions/',
        view=SubscribtionView.as_view(),
        name='user-subscribtion'
    ),
    path(
        route='users/<int:pk>/',
        view=UserDetailView.as_view(),
        name='user-detail'
    ),
    path(
        route='users/<int:pk>/subscribe/',
        view=SubscribeView.as_view(),
        name='user-subscribe'
    ),
    path(
        route='tags/',
        view=TagListView.as_view(),
        name='tag-list'
    ),
    path(
        route='tags/<int:pk>/',
        view=TagDetailView.as_view(),
        name='tag-detail'
    ),
    path(
        route='ingredients/',
        view=IngredientListView.as_view(),
        name='ingredient-list'
    ),
    path(
        route='ingredients/<int:pk>/',
        view=IngredientDetailView.as_view(),
        name='ingredient-detail'
    ),
    path(
        route='recipes/',
        view=RecipeListView.as_view(),
        name='recipe-list'
    ),
    path(
        route='recipes/<int:pk>/',
        view=RecipeDetailView.as_view(),
        name='recipe-detail'
    ),
    path(
        route='recipes/<int:pk>/favorite/',
        view=FavoriteView.as_view(),
        name='favorite'
    ),
    path(
        route='recipes/<int:pk>/shopping_cart/',
        view=ShoppingView.as_view(),
        name='shopping'
    ),
    path(
        route='recipes/download_shopping_cart/',
        view=DownloadShoppingCartView.as_view(),
        name='download-shopping'
    ),
]
